# Generated by Django 5.0.2 on 2024-02-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='category',
            field=models.CharField(default='Food', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(default='Food', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
