# Generated by Django 5.0.6 on 2024-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_beverage_category_alter_food_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
