# Generated by Django 5.0.2 on 2024-02-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_testi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='table_number',
            new_name='number_of_table',
        ),
    ]
