# Generated by Django 5.0.2 on 2024-02-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_table_number_table_number_of_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='beverage',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='food',
        ),
        migrations.DeleteModel(
            name='Testi',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
