# Generated by Django 4.2.11 on 2024-06-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_paid_orderitem_paid_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='paid_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
